"use client";

import { createContext, useContext, useState, ReactNode } from "react";

type Language = "ru" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    ru: {
      "nav.home": "Дом",
      "nav.create": "Сделать",
      "nav.edit": "Инструменты",
      "nav.apps": "Приложения",
      "nav.library": "Библиотека",
      "nav.profile": "Профиль",
      "home.title": "Делай с помощью ИИ",
      "home.subtitle": "Генерируй изображения, видео и аудио одним кликом",
      "prompt.placeholder": "Опишите, что хотите сделать...",
      "prompt.create": "Сделать",
      "type.image": "Изображение",
      "type.image.sub": "Делайте потрясающие визуальные эффекты из текста",
      "type.video": "Видео",
      "type.video.sub": "Оживите свои идеи с помощью ИИ-видео",
      "type.audio": "Аудио",
      "type.audio.sub": "Генерируйте музыку и голос из текста",
      "settings.ratio": "Соотношение сторон",
      "settings.quality": "Качество",
      "settings.model": "Модель",
      "settings.more": "Ещё",
      "section.create": "Сделать",
      "section.edit": "Редактировать",
      "section.edit.sub": "Трансформируйте и улучшайте ваш контент",
      "section.apps": "Приложения",
      "section.apps.sub": "Специализированные ИИ-инструменты для любых задач",
        "edit.removeBg": "Удалить фон",
        "edit.removeBg.sub": "Удаление фона в один клик",
        "edit.enhance": "Улучшить качество",
        "edit.enhance.sub": "Увеличивайте разрешение до 4K",
          "edit.expand": "Расширить",
          "edit.expand.sub": "Дорисовка краев изображения",
          "app.stylist": "Стилист",
      "app.stylist.sub": "Найдите свой идеальный стиль",
      "app.faceSwap": "Замена лица",
      "app.faceSwap.sub": "Бесшовное наложение лиц",
      "app.relight": "Освещение",
      "app.relight.sub": "Профессиональный свет на фото",
      "app.restore": "Восстановить фото",
      "app.restore.sub": "Оживите старые и размытые фото",
      "app.ghibli": "Студия Гибли",
      "app.ghibli.sub": "Превратите фото в аниме-шедевр",
      "app.product": "Карточка товара",
      "app.product.sub": "Профессиональные фото для маркетплейсов",
      "library.title": "Библиотека",
      "library.all": "Все",
      "library.images": "Изображения",
      "library.videos": "Видео",
      "library.audio": "Аудио",
      "library.newest": "Сначала новые",
      "library.oldest": "Сначала старые",
      "action.download": "Скачать",
      "action.share": "Поделиться",
      "action.remix": "Ремикс",
      "action.upscale": "Увеличить",
      "action.animate": "Анимировать",
      "action.delete": "Удалить",
      "action.like": "Нравится",
      "action.folder": "В папку",
      "profile.title": "Профиль",
      "profile.balance": "Баланс",
      "profile.credits": "кредитов",
      "profile.plan": "Текущий тариф",
      "profile.plans": "Сделай больше",
      "profile.buyCredits": "Купить кредиты",
      "profile.settings": "Настройки",
      "profile.referral": "Реферальная ссылка",
      "plan.free": "Бесплатный",
      "plan.starter": "Стартер",
      "plan.pro": "Профессионал",
      "plan.enterprise": "Бизнес",
        "landing.hero": "Генерируй контент с ИИ",
        "landing.heroSub": "Сделай что угодно в ИИ — просто",
        "landing.cta": "Начать бесплатно",
      "landing.features": "Возможности",
      "landing.feature1": "Изображения",
      "landing.feature1Desc": "Делайте уникальные изображения любого стиля",
    "landing.feature2": "Видео",
    "landing.feature2Desc": "Превращайте идеи в динамичные видеоролики",
    "landing.feature3": "Аудио",
    "landing.feature3Desc": "Генерируйте музыку и звуковые эффекты",
    "audio.generateLyrics": "Сгенерировать текст",
    "audio.randomStyles": "Случайные стили",
    "audio.instrumental": "Инструментал",
    "audio.lyrics": "Текст песни",
    "audio.style": "Стиль",
    "cost": "Стоимость",
    "credits": "кредитов",
    "drag.hint": "Добавить",
    "drag.click": "нажмите для загрузки",
  },
    en: {
      "nav.home": "Home",
      "nav.create": "Create",
      "nav.edit": "Tools",
      "nav.apps": "Apps",
      "nav.library": "Library",
      "nav.profile": "Profile",
      "home.title": "Create with AI",
      "home.subtitle": "Generate images, videos and audio with one click",
      "prompt.placeholder": "Describe what you want to create...",
      "prompt.create": "Create",
      "type.image": "Image",
      "type.image.sub": "Create stunning visuals from text",
      "type.video": "Video",
      "type.video.sub": "Bring your ideas to life with AI video",
      "type.audio": "Audio",
      "type.audio.sub": "Generate music and voice from text",
      "settings.ratio": "Aspect Ratio",
      "settings.quality": "Quality",
      "settings.model": "Model",
      "settings.more": "More",
      "section.create": "Create",
      "section.edit": "Edit",
      "section.edit.sub": "Transform and enhance your content",
      "section.apps": "Apps",
      "section.apps.sub": "Specialized AI tools for every task",
        "edit.removeBg": "Remove Background",
        "edit.removeBg.sub": "Remove background in one click",
        "edit.enhance": "Enhance Quality",
        "edit.enhance.sub": "Increase resolution up to 4K",
          "edit.expand": "Expand",
          "edit.expand.sub": "Outpaint image borders",
          "app.stylist": "Stylist",
      "app.stylist.sub": "Find your perfect style",
      "app.faceSwap": "Face Swap",
      "app.faceSwap.sub": "Seamless face replacement",
      "app.relight": "Relight",
      "app.relight.sub": "Professional light for photos",
      "app.restore": "Restore Photo",
      "app.restore.sub": "Revive old and blurry photos",
      "app.ghibli": "Studio Ghibli",
      "app.ghibli.sub": "Turn photos into anime masterpieces",
      "app.product": "Product Card",
      "app.product.sub": "Professional marketplace visuals",
      "library.title": "Library",
    "library.all": "All",
    "library.images": "Images",
    "library.videos": "Videos",
    "library.audio": "Audio",
    "library.newest": "Newest First",
    "library.oldest": "Oldest First",
    "action.download": "Download",
    "action.share": "Share",
    "action.remix": "Remix",
    "action.upscale": "Upscale",
    "action.animate": "Animate",
    "action.delete": "Delete",
    "action.like": "Like",
    "action.folder": "Add to Folder",
    "profile.title": "Profile",
    "profile.balance": "Balance",
    "profile.credits": "credits",
    "profile.plan": "Current Plan",
      "profile.plans": "Do more",
    "profile.buyCredits": "Buy Credits",
    "profile.settings": "Settings",
    "profile.referral": "Referral Link",
    "plan.free": "Free",
    "plan.starter": "Starter",
    "plan.pro": "Professional",
    "plan.enterprise": "Enterprise",
    "landing.hero": "Generate Content with AI",
    "landing.heroSub": "Images, videos and audio in seconds",
    "landing.cta": "Start Free",
    "landing.features": "Features",
    "landing.feature1": "Images",
    "landing.feature1Desc": "Create unique images in any style",
    "landing.feature2": "Video",
    "landing.feature2Desc": "Turn ideas into dynamic videos",
    "landing.feature3": "Audio",
    "landing.feature3Desc": "Generate music and sound effects",
    "audio.generateLyrics": "Generate Lyrics",
    "audio.randomStyles": "Random Styles",
    "audio.instrumental": "Instrumental",
    "audio.lyrics": "Lyrics",
    "audio.style": "Style",
    "cost": "Cost",
    "credits": "credits",
    "drag.hint": "Add",
    "drag.click": "click to upload",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ru");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
