export const AUDIO_STYLES = [
    'synthwave',
    'vaporwave',
    'chillwave',
    'darkwave',
    'shoegaze',
    'post-punk',
    'trip-hop',
    'downtempo',
    'nu-disco',
    'witch house',
    'dream pop',
    'krautrock',
    'math rock',
    'noise rock',
    'sludge metal',
    'drone',
    'glitch',
    'breakcore',
    'jungle',
    'footwork',
    'grime',
    'uk garage',
    'happy hardcore',
    'gabber',
    'psytrance',
    'goa trance',
    'acid house',
    'deep house',
    'dub techno',
    'minimal',
    'idm',
    'braindance',
    'wonky',
    'future garage',
    'post-dubstep',
    'bass music',
] as const;

export type AudioStyle = typeof AUDIO_STYLES[number];
